### PR TITLE
Update constants for Home Assistant 2024

### PR DESCRIPTION
**Pull request by gogades**
Addresses issue #16 - all warnings gone in HA 2024.8.1

Also added a bit of robustness for missing keys and fixed the tempunits config option.

### CODE REVIEW

**Comment by mww012** [comment]
Hey @gogades.  Thanks for putting in this work.  I haven't been able to get to any of this fun stuff lately.  I'll go ahead and merge this in.

**Comment by mww012** [comment]
My HVAC unit died and was replaced with a different unit so I can't test this unfortunately.  I should probably find someone to transfer the repo to.  Would you be interested?

**Comment by gogades** [comment]
@mww012 Sure, I'd be happy to take it over.  Thanks for all the work you did to get us here, it works very well!

**Comment by mww012** [comment]
@gogades I'm happy to transfer that over.  Never done a transfer before but I'm sure we can figure it out.  It would also make sense to transfer mww012/pyinfinitive repo as that's the underlying python library hosted on pypi.  If that's more than you want to take on I can also give you collaborator rights to both repos.

Either way works for me.  Just let me know.

**Comment by gogades** [comment]
@mww012  That makes a lot of sense and I'm happy to take over both.  It's not a ton of code.  I've never done a transfer either so I'm not sure what's invovled.  LMK if you need anything from me.

**Comment by mww012** [comment]
Cool.  I'll start digging through the transfer process.  Once it's done I'll probably fork the repo so we still have something that lives at github.com/mww012/<repo name> so we don't break existing installs.

**Comment by mww012** [comment]
@gogades Well transferring is pretty straight forward.  You should get an email requesting to accept the transfer for the pyinfinitive repository.  Figure I'd start with that one.  The transfer acceptance is good for 24 hours.  If you don't see it in time let me know and I can try again.

Github will do automatic forwarding/redirection from mww012/<repo name> to gogades/<repo name> so I don't have to fork anything!  This whole transfer thing is pretty slick.

**Comment by gogades** [comment]
@mww012  The transfer is really slick - I tried to clone from both `gogades/pyinfinitive`  and `mww012/pyinfinitive` and it works just fine so nothing that depends on the repo would break.

**Comment by mww012** [comment]
@gogades I think you'll have to delete your fork of hass-infinitive.  The transfer for that one griped that gogades/hass-infinitive already existed.

**Comment by gogades** [comment]
@mww012  Ok I nuked it, let it rip!

**Comment by mww012** [comment]
@gogades Done!

**Comment by gogades** [comment]
Thank you so much for writing and maintaining this super useful software, @mww012 !

**Comment by mww012** [comment]
@gogades Awesome!  I'm sure you'll see pretty quickly that I'm not a dev at my day job.  I'm a network engineer who's a nerd so I enjoy these things as a side project.  Feel free to ask anything as you're working through this.  I really appreciate you taking this on.

**Comment by blhoward2** [comment]
@gogades Can you make a new release with these changes? HACS still only picks up 0.9. Also, you need to update your repo in the instructions where you add a custom repo.

**Comment by sparment** [comment]
@blhoward2 did you figure this out? I originally had the mww012/hass-infinitive repo in HACS, but now my HACS integration seems to have automatically pulled up the gogades/hass-infinitive custom repo. I'm not familiar with merging and whatnot, so I guess this was intended to happen. But I'm still getting the same errors I was having before on issue #16

**Comment by blhoward2** [comment]
I haven't really focused on it to be honest, as I didn't hear back.

**Comment by gogades** [comment]
@blhoward2 @sparment  I've made a new release (v0.0.11) with the constant changes, that should resolve the  warning messages you were seeing.  I tested with the latest official release of HA (2024.12.1).

**Comment by sparment** [comment]
Awesome! I can confirm the release fixed the warnings. Thanks

**Pull request merged**
